import { NavItem } from "@/types/navigation";
import { RoadmapPhase } from "@/types/roadmap";

export const NAVIGATION_ITEMS: NavItem[] = [
  {
    id: "theory",
    moduleNumber: 1,
    title: "Học Ngữ Pháp",
    shortTitle: "Lý Thuyết",
    description: "14 Ngày Cứu Ngữ Pháp Cốt Lõi và các cấu trúc nâng Band kèm kiểm tra nhanh.",
    href: "/theory",
    iconName: "BookOpen",
    status: "active",
    badge: "14 bài cứu ngữ pháp (14 ngày)",
    highlightColor: "text-red-700 dark:text-red-400 bg-red-500/10 border-red-500/20",
    estimatedTime: "10-15 phút/bài",
  },
  {
    id: "practice",
    moduleNumber: 2,
    title: "Luyện 4 Kỹ Năng",
    shortTitle: "Luyện Tập",
    description: "Phòng luyện Nghe, Đọc, Viết, Nói chia đôi màn hình tiện theo dõi.",
    href: "/practice",
    iconName: "Zap",
    status: "active",
    badge: "Nghe • Đọc • Viết • Nói",
    highlightColor: "text-amber-500 bg-amber-500/10 border-amber-500/20",
    estimatedTime: "Theo từng ca học",
  },
  {
    id: "grading",
    moduleNumber: 3,
    title: "Chấm Bài Tự Động",
    shortTitle: "Chấm Bài AI",
    description: "Chấm bài Writing và Speaking nhận kết quả ngay theo chuẩn khảo thí.",
    href: "/grading",
    iconName: "PenTool",
    status: "active",
    badge: "Chấm tức thì",
    highlightColor: "text-rose-500 bg-rose-500/10 border-rose-500/20",
    estimatedTime: "Phản hồi <10s",
  },
  {
    id: "vocab",
    moduleNumber: 4,
    title: "Sổ Từ Vựng",
    shortTitle: "Từ Vựng",
    description: "Học từ mới và tự động nhắc ôn lại đúng ngày để không bao giờ quên.",
    href: "/vocab",
    iconName: "Brain",
    status: "active",
    badge: "Nạp từ mới",
    highlightColor: "text-purple-500 bg-purple-500/10 border-purple-500/20",
    estimatedTime: "10-15 phút/ngày",
  },
  {
    id: "error-bank",
    moduleNumber: 5,
    title: "Sổ Tay Lỗi Sai",
    shortTitle: "Lỗi Cần Tránh",
    description: "Ghi lại những câu bạn làm sai khi luyện tập để nhắc bạn không mắc lại.",
    href: "/error-bank",
    iconName: "ShieldAlert",
    status: "active",
    badge: "0 lỗi cần sửa",
    highlightColor: "text-emerald-500 bg-emerald-500/10 border-emerald-500/20",
    estimatedTime: "Tự động gom lỗi",
  },
  {
    id: "ai-coach",
    moduleNumber: 6,
    title: "Luyện Nói Cùng Giám Khảo",
    shortTitle: "Luyện Nói AI",
    description: "Nói chuyện và trả lời câu hỏi trực tiếp với giám khảo ảo để luyện phản xạ.",
    href: "/ai-coach",
    iconName: "Bot",
    status: "active",
    badge: "Phỏng vấn 1-1",
    highlightColor: "text-red-700 dark:text-red-400 bg-red-500/10 border-red-500/20",
    estimatedTime: "Phản xạ thực tế",
  },
];

export const ROADMAP_PHASES: RoadmapPhase[] = [
  {
    id: 1,
    phaseNumber: 1,
    title: "Giai Đoạn 1: 14 Ngày Cứu Ngữ Pháp Nền Tảng & Xây Gốc",
    subtitle: "14 Ngày Phục Hồi Ngữ Pháp Cốt Lõi, Xóa Dịch Word-by-Word & 800 Từ Nền Tảng",
    targetRange: "Band 4.5 ➔ 5.5",
    duration: "Ngày 1 - 14: Cứu Ngữ Pháp Cấp Tốc (19/9 - 2/10/2026)",
    status: "active",
    progressPercent: 0,
    description: "14 ngày tập trung cao độ lấp trọn vẹn lỗ hổng ngữ pháp cốt lõi (1 bài/ngày), xóa bỏ tư duy dịch thô word-by-word, nạp 800 từ vựng nền tảng theo quy luật Nạp trước - Xả sau: Reading (Nạp) ➔ Listening (Nạp) ➔ Writing (Xả) ➔ Speaking (Xả).",
    focusAreas: ["Hiện tại đơn & Quá khứ đơn", "Hiện tại hoàn thành & Bị động", "Mệnh đề quan hệ & Liên từ", "Xóa phản xạ dịch word-by-word"],
    milestones: [
      { id: "m1", title: "Hoàn thành 14 bài vi mô cứu ngữ pháp (1 bài/ngày từ 19/9 đến 2/10)", completed: false },
      { id: "m2", title: "Xóa triệt để phản xạ dịch word-by-word & làm chủ To Be vs Action Verbs", completed: false },
      { id: "m3", title: "Vượt qua bài kiểm định tốt nghiệp 14 ngày cứu ngữ pháp lên Band 5.5", completed: false },
    ],
    unlockedModulesCount: 5,
    totalModulesCount: 5,
  },
  {
    id: 2,
    phaseNumber: 2,
    title: "Giai Đoạn 2: Chiến Thuật 4 Kỹ Năng & 2.500 Từ Chuyên Ngành",
    subtitle: "Kho Từ Passage 3 (Môi Trường, Tâm Lý, Công Nghệ) & Dàn Bài PEEL",
    targetRange: "Band 5.5 ➔ 6.5",
    duration: "Ngày 32 - 77 (19/10 - 3/12/2026)",
    status: "locked",
    progressPercent: 0,
    description: "Làm chủ 14 dạng Reading, cấu trúc PEEL Task 2, mở rộng kho 2.000 – 2.500 từ vựng chuyên ngành phục vụ mục tiêu Reading 8.5 và giải đề Cam 14-16.",
    focusAreas: ["Kho 2.500 từ chuyên ngành Passage 3", "Dàn bài PEEL & Luận cứ Toulmin", "Luyện đề Cam 14, 15, 16", "Viết Task 1 & Task 2 ép giờ"],
    milestones: [
      { id: "m4", title: "Nạp 2.000+ từ vựng chuyên ngành Passage 3 (Môi trường, Tâm lý, Công nghệ...)", completed: false },
      { id: "m5", title: "Giải trọn vẹn Cam 14, 15, 16 và áp dụng khung PEEL", completed: false },
      { id: "m6", title: "Vượt qua bài thi thử Ngày 77 (Mục tiêu Band 6.5)", completed: false },
    ],
    unlockedModulesCount: 0,
    totalModulesCount: 5,
  },
  {
    id: 3,
    phaseNumber: 3,
    title: "Giai Đoạn 3: Luyện Đề Về Đích & Đại Chung Kết 7.5",
    subtitle: "Thi Thử Ép Giờ, Bẻ Bẫy Cam 17-19 & Chấm AI Khắt Khe",
    targetRange: "Band 6.5 ➔ 7.5+",
    duration: "Ngày 78 - 165 (4/12/2026 - 1/3/2027)",
    status: "locked",
    progressPercent: 0,
    description: "Giải đề cường độ cao Cambridge 17-19, rèn luyện áp lực phòng thi thật, chấm AI khắt khe chuẩn British Council/IDP và Đại Chung Kết ngày 1/3/2027.",
    focusAreas: ["Thi thử Full Mock Test áp lực thật", "Tư duy phản biện Speaking Part 3", "Văn phong học thuật Band 8+", "Khóa chặt lỗi sai còn sót lại"],
    milestones: [
      { id: "m7", title: "Hoàn thành các bài Full Test định kỳ Cam 17-19", completed: false },
      { id: "m8", title: "Khóa sạch lỗi sai và bẫy paraphrase tinh vi", completed: false },
      { id: "m9", title: "Đại Chung Kết ngày 165 (1/3/2027) cán đích Band 7.5+", completed: false },
    ],
    unlockedModulesCount: 0,
    totalModulesCount: 5,
  },
];
