/**
 * Mock Passage 3 Epistemic Concept Mapping & Abstract Discourse Data
 * IELTS Reading Passage 3 Cognitive Anatomy (Band 7.5 - 8.5+)
 */

import { Passage3EpistemicItem } from '../lib/epistemicGraphParser';

export const MOCK_PASSAGE3_EPISTEMIC_DATA: Passage3EpistemicItem[] = [
  {
    id: 'p3-01',
    title: 'The Metaphysics of Consciousness & The Hard Problem',
    subtitle: 'From Reductive Neuro-computationalism to Phenomenological Qualia',
    category: 'Philosophy of Mind & Cognitive Neuroscience',
    wordCount: 940,
    paragraphs: [
      `[Paragraph 1] For centuries, the nature of conscious experience was relegated to the mystical domain of metaphysics. In recent decades, however, the unprecedented ascent of functional neuroimaging and cognitive electrophysiology has tempted contemporary science to proclaim that the enigma of human sentience is on the brink of definitive resolution. By mapping specific neural correlates to cognitive operations—such as visual processing in the striate cortex or working memory manipulation in the dorsolateral prefrontal regions—investigators have accumulated immense empirical catalogues detailing how the cerebral apparatus processes external stimuli. Yet, beneath this empirical triumph lies a profound, unaddressed conceptual abyss: explaining how electrochemical transmissions across synaptic clefts coalesce into the raw, qualitative richness of subjective experience.`,

      `[Paragraph 2] This conceptual impasse was crystallized by philosopher David Chalmers through his seminal delineation between the "easy problems" and the "hard problem" of consciousness. The easy problems, according to Chalmers, encompass functional and computational mechanisms: how the brain discriminates perceptual data, focuses attentional resources, integrates environmental information, and executes linguistic reports. Although technologically formidable, these questions belong strictly to the mechanistic domain and are, in principle, susceptible to standard neurobiological methodologies. In stark contrast, the Hard Problem asks why the execution of these physical and computational functions should be accompanied by an inner mental life at all. Why should the firing of neurons in the visual cortex produce the vivid sensation of crimson or the bittersweet pang of grief, rather than proceeding in total phenomenological darkness?`,

      `[Paragraph 3] To demonstrate the logical vulnerability of reductive physicalism, Chalmers formulated the thought experiment of "Philosophical Zombies"—hypothetical entities physically, behaviorally, and computationally identical to ordinary humans in every microphysical detail, yet entirely bereft of subjective qualia. If such creatures are logically conceivable, Chalmers argues, then conscious phenomenology cannot be logically deduced from, or reduced to, mere physical structure. This position, often termed Property Dualism, posits that conscious experience represents a fundamental, irreducible feature of the universe, akin to mass, space-time, or electric charge. Proponents such as Thomas Nagel famously reinforced this stance by arguing that no amount of exhaustive objective data regarding a bat's echolocation apparatus can illuminate "what it is like" for the bat to perceive the world from its first-person perspective.`,

      `[Paragraph 4] Unsurprisingly, Chalmers’ formulation has ignited fierce repudiation from eliminative materialists and computational theorists. Foremost among the skeptics is Daniel Dennett, who dismisses the Hard Problem as a seductive Cartesian illusion generated by flawed cognitive intuitions. Dennett contends that qualia, far from being an irreducible metaphysical substance, are an illusory byproduct of multiple parallel drafting processes occurring throughout the brain. In Dennett’s view, once science provides an exhaustive functional explanation for all the "easy problems"—how we react, discriminate, store, and verbalize information—there is no mysterious, leftover "residue" of consciousness requiring explanation. To insist otherwise, Dennett argues, is to commit a category mistake, comparable to understanding every operational gear, spring, and escapement of a mechanical watch yet insisting that one has not yet discovered its "time-telling essence."`,

      `[Paragraph 5] Aligning closely with Dennett’s skepticism, neurophilosopher Patricia Churchland asserts that dualistic appeals to mysterious, irreducible properties merely reflect current scientific ignorance rather than genuine metaphysical boundaries. Churchland draws historical parallels to nineteenth-century vitalism—the widespread belief that living organisms were animated by a non-physical "vital spark" (elan vital) that could never be elucidated by biochemistry. Just as organic chemistry thoroughly demystified the vital spark through molecular biology, Churchland maintains that mature co-evolutionary neuroscience will ultimately dissolve the hard problem without resorting to dualist concessions.`,

      `[Paragraph 6] Nevertheless, an increasing cadre of contemporary theorists argue that both dogmatic reductionism and classical dualism remain trapped in conceptual dead ends. Neurologist Antonio Damasio and cognitive scientist Anil Seth have proposed frameworks rooted in predictive processing and embodied homeostatic regulation. Seth suggests that the brain is essentially a "prediction machine" that actively generates a "controlled hallucination" of the world and the self to sustain physiological viability. Under this view, consciousness is deeply intertwined with biological embodiment and visceral self-preservation, rather than disembodied computational algorithms or abstract metaphysical properties.`,

      `[Paragraph 7] In synthesizing these polarized factions, one is led to conclude that while Dennett and Churchland rightly warn against mystical obscurantism, their dismissive stance toward subjective phenomenology remains intellectually unsatisfying. The undeniable reality of first-person experience cannot be simply waved away as an irrelevant error of human introspection. A truly comprehensive science of mind must neither retreat into untestable dualism nor collapse into naive physicalism. Instead, the path forward likely demands a radical epistemological evolution: developing formal mathematical and phenomenological bridges capable of correlating the topological structures of conscious awareness with the dynamic, non-linear neurodynamics of the living organism.`
    ],
    nodes: [
      {
        id: 'node-chalmers',
        label: 'David Chalmers',
        type: 'proponent',
        roleTitle: 'Philosopher of Mind (ANU / NYU)',
        summary: 'Formulated the Hard Problem and the Philosophical Zombie thought experiment, arguing qualia is an irreducible property.',
        paragraphIndex: 2,
        keyQuotes: ['The Hard Problem asks why computational functions are accompanied by an inner life.'],
        x: 180,
        y: 110,
        domain: 'Philosophy / Dualism'
      },
      {
        id: 'node-hard-problem',
        label: 'The Hard Problem of Consciousness',
        type: 'concept',
        roleTitle: 'Core Construct',
        summary: 'The puzzle of why physical synaptic firings give rise to subjective, qualitative experiential feeling (qualia).',
        paragraphIndex: 2,
        keyQuotes: ['Why should the firing of neurons produce the vivid sensation of crimson rather than total darkness?'],
        x: 400,
        y: 70,
        domain: 'Epistemic Concept'
      },
      {
        id: 'node-dennett',
        label: 'Daniel Dennett',
        type: 'skeptic',
        roleTitle: 'Cognitive Philosopher (Tufts)',
        summary: 'Dismisses qualia as an illusion, asserting that fully answering the easy functional problems dissolves the mystery.',
        paragraphIndex: 4,
        keyQuotes: ['Qualia is an illusory byproduct of multiple parallel drafting processes.'],
        x: 620,
        y: 110,
        domain: 'Eliminative Materialism'
      },
      {
        id: 'node-nagel',
        label: 'Thomas Nagel',
        type: 'proponent',
        roleTitle: 'Philosopher (NYU)',
        summary: 'Argues objective physical descriptions cannot capture the subjective "what-it-is-like" first-person phenomenology.',
        paragraphIndex: 3,
        keyQuotes: ['No objective data on bat echolocation can reveal what it is like for the bat.'],
        x: 130,
        y: 250,
        domain: 'Phenomenology'
      },
      {
        id: 'node-churchland',
        label: 'Patricia Churchland',
        type: 'skeptic',
        roleTitle: 'Neurophilosopher (UC San Diego)',
        summary: 'Compares dualism to 19th-century vitalism, arguing advanced neuroscience will naturally demystify consciousness.',
        paragraphIndex: 5,
        keyQuotes: ['Dualist appeals merely reflect current scientific ignorance like vitalism.'],
        x: 670,
        y: 250,
        domain: 'Neuro-reductionism'
      },
      {
        id: 'node-predictive-mind',
        label: 'Embodied Predictive Processing',
        type: 'concept',
        roleTitle: 'Emerging Framework (Seth & Damasio)',
        summary: 'Views consciousness as a biologically grounded controlled hallucination evolved for visceral homeostasis.',
        paragraphIndex: 6,
        keyQuotes: ['The brain actively generates a controlled hallucination to sustain physiological viability.'],
        x: 400,
        y: 280,
        domain: 'Embodied Cognitive Science'
      },
      {
        id: 'node-author-stance',
        label: 'Authorial Epilogue',
        type: 'author_stance',
        roleTitle: 'Synthesis & Epistemic Verdict',
        summary: 'Rejects both eliminative dismissal of qualia and mystical dualism, urging formal mathematical-phenomenological bridges.',
        paragraphIndex: 7,
        keyQuotes: ['A comprehensive science of mind must neither retreat into dualism nor collapse into naive physicalism.'],
        x: 400,
        y: 390,
        domain: 'Author Stance'
      }
    ],
    edges: [
      {
        id: 'edge-1',
        source: 'node-chalmers',
        target: 'node-hard-problem',
        relation: 'originates_from',
        label: 'Khởi xướng & Định nghĩa',
        evidenceSnippet: 'This conceptual impasse was crystallized by philosopher David Chalmers through his seminal delineation...',
        paragraphIndex: 2
      },
      {
        id: 'edge-2',
        source: 'node-nagel',
        target: 'node-chalmers',
        relation: 'supports',
        label: 'Ủng hộ tính bất khả quy',
        evidenceSnippet: 'Proponents such as Thomas Nagel famously reinforced this stance by arguing...',
        paragraphIndex: 3
      },
      {
        id: 'edge-3',
        source: 'node-dennett',
        target: 'node-hard-problem',
        relation: 'undermines',
        label: 'Bác bỏ coi là ảo ảnh',
        evidenceSnippet: 'Daniel Dennett, who dismisses the Hard Problem as a seductive Cartesian illusion...',
        paragraphIndex: 4
      },
      {
        id: 'edge-4',
        source: 'node-churchland',
        target: 'node-dennett',
        relation: 'supports',
        label: 'Mở rộng quy giản thần kinh',
        evidenceSnippet: 'Aligning closely with Dennett’s skepticism, neurophilosopher Patricia Churchland asserts...',
        paragraphIndex: 5
      },
      {
        id: 'edge-5',
        source: 'node-predictive-mind',
        target: 'node-hard-problem',
        relation: 'qualifies',
        label: 'Tái định hình qua sinh học',
        evidenceSnippet: 'Seth suggests that the brain is essentially a prediction machine that generates a controlled hallucination...',
        paragraphIndex: 6
      },
      {
        id: 'edge-6',
        source: 'node-author-stance',
        target: 'node-hard-problem',
        relation: 'qualifies',
        label: 'Tổng hợp biện chứng C1/C2',
        evidenceSnippet: 'A truly comprehensive science of mind must neither retreat into untestable dualism nor collapse into naive physicalism.',
        paragraphIndex: 7
      }
    ],
    constructs: [
      {
        id: 'c1',
        name: 'Qualia / Phenomenological Experience',
        definition: 'The intrinsic, subjective, qualitative properties of conscious mental states (e.g. the specific redness of red, the taste of wine).',
        implications: 'Creates the core epistemological hurdle: objective third-person science cannot directly capture first-person subjective sensations.',
        collocations: ['subjective qualia', 'phenomenological richness', 'experiential texture', 'first-person ontology']
      },
      {
        id: 'c2',
        name: 'Reductive Physicalism',
        definition: 'The ontological thesis that all mental phenomena can be completely explained and accounted for by physical, biological laws.',
        implications: 'Struggles to answer why physical processes are accompanied by inner experiential states.',
        collocations: ['reductive physicalism', 'mechanistic explanation', 'neural correlates', 'eliminative materialism']
      },
      {
        id: 'c3',
        name: 'Philosophical Zombies',
        definition: 'A hypothetical entity identical in every physical and functional aspect to a human, but having zero conscious awareness.',
        implications: 'Used to logically detach functional computation from subjective conscious experience.',
        collocations: ['logical conceivability', 'zombie thought experiment', 'property dualism', 'epiphenomenalism']
      }
    ],
    factions: {
      proponents: [
        {
          name: 'David Chalmers & Thomas Nagel',
          institution: 'NYU / Australian National University',
          coreClaim: 'Consciousness is an irreducible fundamental property of reality; functional explanations cannot account for subjective qualia.',
          methodology: 'Conceptual analysis, thought experiments (Zombies, Bat phenomenology), mathematical dualism.'
        }
      ],
      skeptics: [
        {
          name: 'Daniel Dennett & Patricia Churchland',
          institution: 'Tufts University / UC San Diego',
          coreClaim: 'Qualia is an illusion; explaining all cognitive and computational sub-functions completely solves the puzzle of mind.',
          methodology: 'Functionalism, heterophenomenology, historical analogies to the demise of biological vitalism.'
        }
      ]
    },
    authorStance: {
      stanceType: 'cautious_synthesis',
      stanceTitle: 'Biện Chứng Hợp Nhất & Thận Trọng Nhận Thức Luận (Cautious Methodological Synthesis)',
      coreThesis: 'Bác bỏ thái độ quy giản cực đoan xem ý thức là ảo ảnh của Dennett, đồng thời từ chối thuyết nhị nguyên huyền bí; kêu gọi xây dựng các mô hình toán học và hiện tượng học kết nối cấu trúc trải nghiệm với động lực học thần kinh phi tuyến tính.',
      keyHedgingExpressions: [
        'while Dennett and Churchland rightly warn against...',
        'remains intellectually unsatisfying',
        'must neither retreat into... nor collapse into...',
        'the path forward likely demands a radical epistemological evolution'
      ],
      concludingParagraphIndex: 7,
      cambridgeTrapExplanation: 'Đề thi Cambridge thường gài bẫy thí sinh Band 6.5 suy diễn rằng tác giả hoàn toàn ủng hộ Chalmers (Dualism) hoặc Dennett (Materialism). Tuy nhiên, tác giả thực chất đứng ở vị thế Tổng hợp phê phán (Critical Synthesis), thừa nhận tính thực tại của Qualia nhưng yêu cầu công cụ khoa học mới.'
    },
    summaryTask: {
      title: 'Summary Completion: The Epistemological Debate on Conscious Experience',
      instructions: 'Complete the summary below by choosing the correct terms from the Box of Options. Write the correct letter (A-J) in boxes 1-5.',
      options: [
        { id: 'opt-A', term: 'phenomenological', ipa: '/fəˌnɑː.mə.nəˈlɑː.dʒɪ.kəl/', definitionEn: 'Relating to subjective, conscious experience and perception.', definitionVi: 'thuộc về hiện tượng học, cảm nhận chủ quan', band: 'C2', isDistractor: false },
        { id: 'opt-B', term: 'reductive', ipa: '/rɪˈdʌk.tɪv/', definitionEn: 'Explaining complex phenomena in overly simplified physical terms.', definitionVi: 'mang tính quy giản cơ học', band: 'C1', isDistractor: false },
        { id: 'opt-C', term: 'illusory', ipa: '/ɪˈluː.sɚ.i/', definitionEn: 'Based on or producing an illusion; not real.', definitionVi: 'mang tính ảo ảnh, đánh lừa nhận thức', band: 'C1', isDistractor: false },
        { id: 'opt-D', term: 'irreducible', ipa: '/ˌɪr.əˈduː.sə.bəl/', definitionEn: 'Not able to be brought to a simpler or more basic state.', definitionVi: 'không thể quy giản, mang tính cốt lõi', band: 'C2', isDistractor: false },
        { id: 'opt-E', term: 'epistemological', ipa: '/ɪˌpɪs.tə.məˈlɑː.dʒɪ.kəl/', definitionEn: 'Relating to the theory of knowledge and how we understand reality.', definitionVi: 'thuộc về nhận thức luận', band: 'C2', isDistractor: false },
        { id: 'opt-F', term: 'computational', ipa: '/ˌkɑːm.pjəˈteɪ.ʃən.əl/', definitionEn: 'Relating to process calculations and algorithms.', definitionVi: 'thuộc về tính toán thuật toán', band: 'C1', isDistractor: true, distractorRationale: 'Dùng để bẫy thí sinh chỉ chú ý đến hoạt động xử lý dữ liệu của não thay vì bản chất trải nghiệm.' },
        { id: 'opt-G', term: 'epiphenomenal', ipa: '/ˌep.ɪ.fəˈnɑː.mə.nəl/', definitionEn: 'A secondary byproduct with no causal power.', definitionVi: 'hiện tượng phụ sinh không có tác động nhân quả', band: 'C2', isDistractor: true, distractorRationale: 'Thuật ngữ triết học phức tạp nhưng không phù hợp với ngữ cảnh ô trống.' },
        { id: 'opt-H', term: 'empirical', ipa: '/ɪmˈpɪr.ɪ.kəl/', definitionEn: 'Based on observation or experiment rather than theory.', definitionVi: 'thực nghiệm, dựa trên quan sát', band: 'C1', isDistractor: true, distractorRationale: 'Bẫy từ vựng nghiên cứu khoa học.' },
        { id: 'opt-I', term: 'vitalist', ipa: '/ˈvaɪ.t̬əl.ɪst/', definitionEn: 'Believing in a mystical life force.', definitionVi: 'thuộc thuyết sinh lực học', band: 'C2', isDistractor: true, distractorRationale: 'Bẫy lịch sử sinh học thế kỷ 19.' },
        { id: 'opt-J', term: 'dogmatic', ipa: '/dɑːɡˈmæt̬.ɪk/', definitionEn: 'Insistently asserting principles without adequate proof.', definitionVi: 'giáo điều, cứng nhắc', band: 'C1', isDistractor: true, distractorRationale: 'Tính từ phê phán nhưng không phải là khái niệm trọng tâm của tóm tắt.' }
      ],
      slots: [
        {
          id: 'slot-1',
          slotNumber: 1,
          preText: 'While contemporary neuroscience has successfully mapped functional brain circuits, it struggles to account for',
          correctTermId: 'opt-A',
          correctTerm: 'phenomenological',
          postText: 'aspects of consciousness—the raw, qualitative sensation of experience known as qualia.',
          explanation: 'Đoạn 1 và 2 nhấn mạnh sự bất lực của khoa học cơ học trong việc giải thích cảm nhận chủ quan ("phenomenological darkness", "raw qualitative richness").',
          epistemicTrap: 'Bẫy chọn "computational" do nhầm lẫn giữa chức năng tính toán cơ học và cảm nhận hiện tượng học nội tâm.'
        },
        {
          id: 'slot-2',
          slotNumber: 2,
          preText: 'In response, David Chalmers proposed the Hard Problem, asserting that subjective awareness is logically',
          correctTermId: 'opt-D',
          correctTerm: 'irreducible',
          postText: 'to physical processes, as demonstrated by the conceivable existence of Philosophical Zombies.',
          explanation: 'Đoạn 3 chỉ rõ lập trường của Chalmers: ý thức là một thuộc tính cơ bản ("fundamental, irreducible feature") không thể suy dẫn từ cấu trúc vật lý.',
          epistemicTrap: 'Bẫy chọn "reductive" vì đọc lướt thấy từ "reductive physicalism" mà không nhận ra Chalmers phản bác quan điểm này.'
        },
        {
          id: 'slot-3',
          slotNumber: 3,
          preText: 'Conversely, materialists like Daniel Dennett dismiss qualia entirely, classifying it as an',
          correctTermId: 'opt-C',
          correctTerm: 'illusory',
          postText: 'artifact created by parallel computational drafting in the brain.',
          explanation: 'Đoạn 4 nêu rõ Dennett coi qualia là "an illusory byproduct of multiple parallel drafting processes".',
          epistemicTrap: 'Bẫy chọn "epiphenomenal" vì nghĩ rằng Dennett thừa nhận qualia tồn tại như một sản phẩm phụ, trong khi ông triệt để phủ nhận nó.'
        },
        {
          id: 'slot-4',
          slotNumber: 4,
          preText: 'Patricia Churchland reinforces this stance by critiquing dualism as an unscientific retreat, arguing that modern neuroscience will supersede',
          correctTermId: 'opt-B',
          correctTerm: 'reductive',
          postText: 'skepticism just as molecular biology overcame vitalism in the 19th century.',
          explanation: 'Đoạn 5 so sánh sự hoài nghi của phe nhị nguyên với thuyết sinh lực học, khẳng định khoa học thần kinh sẽ giải mã cơ học mọi bí ẩn.',
          epistemicTrap: 'Bẫy chọn "vitalist" do thấy từ này xuất hiện trong đoạn văn, nhưng ở đây cần một tính từ bổ nghĩa cho lập luận khoa học.'
        },
        {
          id: 'slot-5',
          slotNumber: 5,
          preText: 'In evaluating the debate, the author contends that dismissing first-person experience is insufficient, advocating instead for a new',
          correctTermId: 'opt-E',
          correctTerm: 'epistemological',
          postText: 'framework capable of mathematically linking subjective awareness with living neurodynamics.',
          explanation: 'Đoạn 7 kết luận rằng con đường phía trước đòi hỏi một cuộc cách mạng nhận thức luận ("radical epistemological evolution").',
          epistemicTrap: 'Bẫy chọn "empirical" vì nghĩ tác giả kêu gọi thêm thí nghiệm, trong khi tác giả yêu cầu khung lý thuyết nhận thức mới.'
        }
      ]
    }
  },
  {
    id: 'p3-02',
    title: 'Linguistic Relativity & The Architecture of Human Cognition',
    subtitle: 'From Sapir-Whorf Determinism to Embodied Spatial Metaphors',
    category: 'Cognitive Linguistics & Psycholinguistics',
    wordCount: 960,
    paragraphs: [
      `[Paragraph 1] Does the mother tongue we speak act as an invisible prism that fundamentally determines how we conceptualize reality, or is language merely an ephemeral superficial dress thrown over an immutable, universal cognitive architecture? This inquiry, known formally as the Principle of Linguistic Relativity or the Sapir-Whorf Hypothesis, represents one of the most contentious battlegrounds in twentieth and twenty-first-century cognitive science. In its most radical formulation—linguistic determinism—language is postulated as a cognitive prison house: the lexical and grammatical boundaries of one’s language irrevocably constrain the limits of what thoughts can be conceived.`,

      `[Paragraph 2] The genesis of this hypothesis traces to linguists Edward Sapir and his student Benjamin Lee Whorf in the 1930s. Whorf’s comparative ethnographic investigations of indigenous American tongues, particularly the Hopi language of Arizona, led him to assert that Hopi lacked European-style notions of chronological, linear time. Because Hopi grammar purportedly treats temporal phenomena not as discrete, countable units (such as "three days" or "ten minutes") but as an ongoing experiential process of "becoming," Whorf deduced that Hopi speakers inhabited a fundamentally divergent metaphysical universe from speakers of Standard Average European languages.`,

      `[Paragraph 3] For nearly four decades following the cognitive revolution of the 1960s, Whorfian relativism was decisively marginalized by mainstream linguistics. Under the formidable intellectual influence of Noam Chomsky, language was recast as a universal biological instinct underpinned by an innate "Universal Grammar" encoded in human genetics. Chomsky argued that beneath surface phonetic and morphological disparities, all human languages share a uniform deep syntactic architecture. In this nativist framework, thought is sovereign: human beings possess an internal mental language ("Mentalese," as termed by cognitive psychologist Steven Pinker), and surface speech acts are simply acoustic output transducers for pre-existing, non-linguistic conceptual primitives. Pinker scathingly dismissed Whorf’s Hopi conclusions, pointing to severe anthropological errors and demonstrating that translation across disparate linguistic systems would be impossible if radical determinism held true.`,

      `[Paragraph 4] However, the turn of the millennium witnessed a dramatic empirical renaissance of neo-Whorfian scholarship, spearheaded by cognitive psycholinguists such as Lera Boroditsky and Stephen Levinson. Rather than resurrecting radical determinism, these researchers championed a refined, probabilistic model known as "weak relativity." By employing rigorous psychophysical experiments and chronometric eye-tracking methodologies, Boroditsky demonstrated that language habits exert profound, subtle influences on perceptual categorization, spatial navigation, and memory encoding.`,

      `[Paragraph 5] A celebrated case study involves the Kuuk Thaayorre, an Australian Aboriginal community in Cape York. Unlike speakers of European languages who rely almost exclusively on egocentric spatial coordinates ("to my left," "behind me"), the Kuuk Thaayorre organize all spatial reference in terms of absolute cardinal directions ("north," "south-southwest"). When asked to arrange sequential chronological photographs of a person aging, English speakers consistently arrange them from left to right, reflecting their writing direction. In startling contrast, Kuuk Thaayorre speakers arrange the sequence strictly from east to west: if facing south, they lay the cards from left to right; if facing north, from right to left; and if facing east, toward the body. Language in this context acts not as an absolute intellectual barrier, but as a continuous cognitive training system that demands hyper-acute environmental orientation.`,

      `[Paragraph 6] Similar subtle effects have been documented in chromatic discrimination. Languages like Russian and Greek distinguish between light blue ("goluboy" in Russian) and dark blue ("siniy") as distinct primary colors rather than shades of a single hue. Electrophysiological studies measuring event-related potentials (ERPs) reveal that Russian speakers exhibit faster automatic neural discrimination at the boundary between light and dark blue than English speakers, indicating that linguistic categories penetrate early visual processing stages rather than merely affecting post-perceptual decision-making.`,

      `[Paragraph 7] Ultimately, evaluating the veracity of linguistic relativity requires discarding simplistic binary dichotomies. The extreme Whorfian claim that language imprisons thought is palpably fallacious, as humans frequently conceptualize emotions, visual aesthetics, and mathematical relationships for which their lexicon lacks precise terms. Conversely, Chomsky’s and Pinker’s insistence that language is a wholly detached, neutral conduit for an immutable Mentalese fails to acknowledge the rich, empirical reality of embodied cultural cognition. Language does not dictate what we are capable of thinking, but through its persistent, habitual grammar and metaphorical frameworks, it gently nudges our attentional spotlight toward specific facets of the world, shaping the subtle textures of human consciousness.`
    ],
    nodes: [
      {
        id: 'node-whorf',
        label: 'Benjamin Lee Whorf',
        type: 'proponent',
        roleTitle: 'Linguist & Ethnographer',
        summary: 'Formulated strong linguistic determinism based on Hopi temporal grammar, arguing language dictates worldview.',
        paragraphIndex: 2,
        keyQuotes: ['Hopi grammar treats time not as countable units but as an ongoing process of becoming.'],
        x: 180,
        y: 110,
        domain: 'Linguistic Determinism'
      },
      {
        id: 'node-relativity-concept',
        label: 'Linguistic Relativity Hypothesis',
        type: 'concept',
        roleTitle: 'Core Construct',
        summary: 'The theoretical proposition that the structure of a language influences its speakers world view and cognitive processes.',
        paragraphIndex: 1,
        keyQuotes: ['Does language act as an invisible prism that determines how we conceptualize reality?'],
        x: 400,
        y: 70,
        domain: 'Epistemic Concept'
      },
      {
        id: 'node-chomsky',
        label: 'Noam Chomsky & Steven Pinker',
        type: 'skeptic',
        roleTitle: 'Universal Grammar & Nativism (MIT / Harvard)',
        summary: 'Reject Whorfian relativity, arguing for innate Universal Grammar and Mentalese, with thought completely independent of surface speech.',
        paragraphIndex: 3,
        keyQuotes: ['Thought is sovereign in an internal language called Mentalese.'],
        x: 620,
        y: 110,
        domain: 'Universal Grammar'
      },
      {
        id: 'node-boroditsky',
        label: 'Lera Boroditsky & Stephen Levinson',
        type: 'proponent',
        roleTitle: 'Cognitive Psycholinguists (Stanford / Max Planck)',
        summary: 'Pioneered Neo-Whorfian empirical revival (spatial orientation in Kuuk Thaayorre, Russian color boundary ERPs).',
        paragraphIndex: 4,
        keyQuotes: ['Language habits exert subtle influences on perceptual categorization and spatial memory.'],
        x: 200,
        y: 260,
        domain: 'Probabilistic Neo-Whorfianism'
      },
      {
        id: 'node-spatial-cognition',
        label: 'Absolute vs Egocentric Spatial Frame',
        type: 'concept',
        roleTitle: 'Empirical Case Study',
        summary: 'Kuuk Thaayorre organizing time and space strictly east-to-west rather than left-to-right.',
        paragraphIndex: 5,
        keyQuotes: ['Kuuk Thaayorre organize space in absolute cardinal directions.'],
        x: 400,
        y: 260,
        domain: 'Cognitive Anthropology'
      },
      {
        id: 'node-author-whorf-stance',
        label: 'Authorial Synthesis',
        type: 'author_stance',
        roleTitle: 'Nuanced Attentional Habituation',
        summary: 'Rejects both radical determinism and pure nativist isolation; language functions as a habitual spotlight orienting cognitive attention.',
        paragraphIndex: 7,
        keyQuotes: ['Language does not dictate thought, but gently nudges our attentional spotlight.'],
        x: 400,
        y: 390,
        domain: 'Author Stance'
      }
    ],
    edges: [
      {
        id: 'edge-w1',
        source: 'node-whorf',
        target: 'node-relativity-concept',
        relation: 'originates_from',
        label: 'Khởi nguồn thuyết quyết định',
        evidenceSnippet: 'The genesis of this hypothesis traces to linguists Edward Sapir and his student Benjamin Lee Whorf...',
        paragraphIndex: 2
      },
      {
        id: 'edge-w2',
        source: 'node-chomsky',
        target: 'node-relativity-concept',
        relation: 'undermines',
        label: 'Bác bỏ bằng Ngữ pháp Phổ quát',
        evidenceSnippet: 'For nearly four decades, Whorfian relativism was decisively marginalized by mainstream linguistics under Noam Chomsky...',
        paragraphIndex: 3
      },
      {
        id: 'edge-w3',
        source: 'node-boroditsky',
        target: 'node-whorf',
        relation: 'qualifies',
        label: 'Tái sinh qua thuyết Tương đối yếu',
        evidenceSnippet: 'Rather than resurrecting radical determinism, these researchers championed a refined model known as weak relativity.',
        paragraphIndex: 4
      },
      {
        id: 'edge-w4',
        source: 'node-boroditsky',
        target: 'node-spatial-cognition',
        relation: 'supports',
        label: 'Dẫn chứng thực nghiệm không gian',
        evidenceSnippet: 'A celebrated case study involves the Kuuk Thaayorre, an Australian Aboriginal community...',
        paragraphIndex: 5
      },
      {
        id: 'edge-w5',
        source: 'node-author-whorf-stance',
        target: 'node-relativity-concept',
        relation: 'qualifies',
        label: 'Lập trường dung hòa C1/C2',
        evidenceSnippet: 'Language does not dictate what we are capable of thinking, but through its persistent grammar, it gently nudges our attentional spotlight.',
        paragraphIndex: 7
      }
    ],
    constructs: [
      {
        id: 'cw1',
        name: 'Linguistic Determinism vs Relativity',
        definition: 'Determinism posits language strictly limits thoughts; relativity posits language patterns subtly bias attentional habits.',
        implications: 'Key test of whether human thought is biologically uniform or culturally malleable.',
        collocations: ['linguistic determinism', 'cognitive constraints', 'weak relativity', 'perceptual categories']
      },
      {
        id: 'cw2',
        name: 'Mentalese / Innatism',
        definition: 'The hypothesis of a universal, non-verbal internal language of thought common to all humans.',
        implications: 'Reduces spoken languages to mere translation mechanisms of pre-formed concepts.',
        collocations: ['internal mental language', 'innate Universal Grammar', 'cognitive primitives', 'surface morphology']
      }
    ],
    factions: {
      proponents: [
        {
          name: 'Benjamin Lee Whorf & Lera Boroditsky',
          institution: 'MIT / Stanford University',
          coreClaim: 'Linguistic structures actively shape perceptual processing, spatial navigation, and categorical memory.',
          methodology: 'Cross-linguistic ethnography, chronometric reaction times, electroencephalography (ERP).'
        }
      ],
      skeptics: [
        {
          name: 'Noam Chomsky & Steven Pinker',
          institution: 'MIT / Harvard University',
          coreClaim: 'Thought occurs in a universal internal code (Mentalese) independent of surface linguistic variation.',
          methodology: 'Generative grammar, evolutionary psychology, universalist cognitive architecture.'
        }
      ]
    },
    authorStance: {
      stanceType: 'qualified_endorsement',
      stanceTitle: 'Định Hướng Chú Ý Thói Quen (Habitual Attentional Spotlight)',
      coreThesis: 'Bác bỏ thuyết giam cầm nhận thức cực đoan của Whorf cổ điển, đồng thời chỉ ra tính phiến diện của thuyết Mentalese cô lập; khẳng định ngôn ngữ là chiếc đèn rọi thói quen uốn nắn sự chú ý của tâm trí.',
      keyHedgingExpressions: [
        'requires discarding simplistic binary dichotomies',
        'is palpably fallacious',
        'fails to acknowledge the rich empirical reality',
        'gently nudges our attentional spotlight'
      ],
      concludingParagraphIndex: 7,
      cambridgeTrapExplanation: 'Bẫy thường gặp là học viên tưởng tác giả bác bỏ hoàn toàn Whorf. Thực chất tác giả bác bỏ "Thuyết Quyết Định Cực Đoan" (Strong Determinism) nhưng tán thành "Thuyết Tương Đối Yếu Thực Nghiệm" (Weak Probabilistic Relativity).'
    },
    summaryTask: {
      title: 'Summary Completion: The Evolution of Linguistic Relativity',
      instructions: 'Complete the summary below using the Box of Options. Choose the correct letter (A-J) for questions 1-5.',
      options: [
        { id: 'opt-A', term: 'deterministic', ipa: '/dɪˌtɝː.mɪˈnɪs.tɪk/', definitionEn: 'Relating to the philosophical idea that all events are strictly determined.', definitionVi: 'mang tính tiền định, áp đặt tuyệt đối', band: 'C1', isDistractor: false },
        { id: 'opt-B', term: 'innate', ipa: '/ɪˈneɪt/', definitionEn: 'Inborn; natural; present from birth.', definitionVi: 'bẩm sinh, di truyền', band: 'C1', isDistractor: false },
        { id: 'opt-C', term: 'habitual', ipa: '/həˈbɪtʃ.u.əl/', definitionEn: 'Done constantly or as a habit.', definitionVi: 'theo thói quen cố hữu', band: 'C1', isDistractor: false },
        { id: 'opt-D', term: 'spatial', ipa: '/ˈspeɪ.ʃəl/', definitionEn: 'Relating to space and position.', definitionVi: 'thuộc về không gian', band: 'C1', isDistractor: false },
        { id: 'opt-E', term: 'universal', ipa: '/ˌjuː.nəˈvɝː.səl/', definitionEn: 'Applicable to all cases or all people.', definitionVi: 'phổ quát, toàn thể', band: 'C1', isDistractor: false },
        { id: 'opt-F', term: 'plasticity', ipa: '/plæsˈtɪs.ə.t̬i/', definitionEn: 'The adaptability of an organism or neural system.', definitionVi: 'tính dẻo dai não bộ', band: 'C2', isDistractor: true, distractorRationale: 'Thuật ngữ thần kinh học nhưng không phải ý tóm tắt.' },
        { id: 'opt-G', term: 'arbitrary', ipa: '/ˈɑːr.bə.trer.i/', definitionEn: 'Based on random choice rather than reason.', definitionVi: 'tùy tiện, ngẫu nhiên', band: 'C1', isDistractor: true, distractorRationale: 'Bẫy từ vựng ngôn ngữ học Saussure.' },
        { id: 'opt-H', term: 'mentalese', ipa: '/ˌmen.təˈliːz/', definitionEn: 'Hypothetical internal language of thought.', definitionVi: 'ngôn ngữ tư duy nội tâm', band: 'C2', isDistractor: true, distractorRationale: 'Danh từ chỉ ngôn ngữ tư duy thay vì tính từ mô tả cơ chế.' },
        { id: 'opt-I', term: 'immutable', ipa: '/ɪˈmjuː.t̬ə.bəl/', definitionEn: 'Unchanging over time or unable to be changed.', definitionVi: 'bất biến, không thể thay đổi', band: 'C2', isDistractor: true, distractorRationale: 'Bẫy tính từ cực đoan.' },
        { id: 'opt-J', term: 'fallacious', ipa: '/fəˈleɪ.ʃəs/', definitionEn: 'Based on a mistaken belief or bad reasoning.', definitionVi: 'sai lầm, ngụy biện', band: 'C2', isDistractor: true, distractorRationale: 'Từ chỉ lỗi logic.' }
      ],
      slots: [
        {
          id: 'slot-1',
          slotNumber: 1,
          preText: 'In its original and most extreme form, the Sapir-Whorf hypothesis posited a strictly',
          correctTermId: 'opt-A',
          correctTerm: 'deterministic',
          postText: 'relationship between language and thought, claiming that lexical limits imprison human conception.',
          explanation: 'Đoạn 1 nêu rõ hình thức cực đoan nhất là "linguistic determinism", xem ngôn ngữ là nhà tù nhận thức ("cognitive prison house").',
          epistemicTrap: 'Bẫy chọn "arbitrary" hoặc "immutable" do không nắm được thuật ngữ chuyên ngành "deterministic".'
        },
        {
          id: 'slot-2',
          slotNumber: 2,
          preText: 'This paradigm was overturned by Noam Chomsky, who argued that language is governed by an',
          correctTermId: 'opt-B',
          correctTerm: 'innate',
          postText: 'biological system shared across all humans, meaning conceptual thought precedes surface speech.',
          explanation: 'Đoạn 3 giải thích thuyết Nativism của Chomsky: ngôn ngữ là bản năng sinh học bẩm sinh ("innate Universal Grammar").',
          epistemicTrap: 'Bẫy chọn "universal" (đã có ở vế sau "shared across all humans") dẫn đến trùng lặp ngữ nghĩa.'
        },
        {
          id: 'slot-3',
          slotNumber: 3,
          preText: 'Chomsky posited that beneath surface differences lies a deeply uniform and',
          correctTermId: 'opt-E',
          correctTerm: 'universal',
          postText: 'syntactic architecture governing human mental operations.',
          explanation: 'Đoạn 3 khẳng định mọi ngôn ngữ chia sẻ một cấu trúc cú pháp chung sâu sắc ("uniform deep syntactic architecture").',
          epistemicTrap: 'Bẫy chọn "innate" nếu đã dùng sai ở câu trước.'
        },
        {
          id: 'slot-4',
          slotNumber: 4,
          preText: 'However, modern studies of the Kuuk Thaayorre revealed that language profoundly impacts',
          correctTermId: 'opt-D',
          correctTerm: 'spatial',
          postText: 'orientation, forcing speakers to calculate cardinal directions continuously.',
          explanation: 'Đoạn 5 phân tích ví dụ cộng đồng Kuuk Thaayorre với hệ tọa độ định hướng không gian tuyệt đối ("spatial coordinates").',
          epistemicTrap: 'Bẫy chọn "plasticity" do nhầm sang tính linh hoạt của não bộ.'
        },
        {
          id: 'slot-5',
          slotNumber: 5,
          preText: 'The author concludes that while language does not imprison thought, its persistent grammar trains a',
          correctTermId: 'opt-C',
          correctTerm: 'habitual',
          postText: 'spotlight, guiding our attention to specific dimensions of reality.',
          explanation: 'Đoạn 7 kết luận: "through its persistent, habitual grammar... it gently nudges our attentional spotlight".',
          epistemicTrap: 'Bẫy chọn "fallacious" do câu có từ phủ định "does not imprison".'
        }
      ]
    }
  },
  {
    id: 'p3-03',
    title: 'The Epistemology of Artificial Intuition & Deep Learning Black Boxes',
    subtitle: 'From High-Dimensional Statistical Induction to Causal Ontology',
    category: 'Computer Science & Philosophy of Technology',
    wordCount: 920,
    paragraphs: [
      `[Paragraph 1] In 2016, when AlphaGo executed Move 37 during its historic match against world champion Lee Sedol, commentators initially branded the maneuver a bizarre, amateurish blunder. It was only dozens of moves later that the genius of the play became manifest: the artificial neural network had discovered an entirely novel, profound strategic principle that had eluded human masters for four millennia. This watershed moment catalyzed a widespread epistemological claim: that deep connectionist architectures have transcended brute computational crunching to achieve genuine "machine intuition." Yet, as multi-layer deep neural networks increasingly govern mission-critical decisions—from medical diagnostics to autonomous defense—computer scientists and philosophers find themselves grappling with a disturbing epistemic predicament: the "Black Box" problem.`,

      `[Paragraph 2] The architecture of deep learning models fundamentally departs from classical symbolic artificial intelligence. Traditional AI operated on explicit, human-readable rules and formal deductive logic (e.g., "if condition X and Y, then execute action Z"). In stark contrast, contemporary deep neural networks consist of hundreds of millions of interconnected artificial neurons organized in dense, hierarchical layers. Through gradient descent and backpropagation across massive datasets, the network optimizes millions of numerical parameters (weights and biases). The model does not acquire abstract semantic concepts; rather, it constructs immensely complex, non-linear geometric manifolds within high-dimensional mathematical vector spaces.`,

      `[Paragraph 3] Leading connectionist pioneers, including Turing Award laureates Geoffrey Hinton and Yann LeCun, argue that this high-dimensional statistical induction mirrors the heuristic, intuitive functioning of the human cerebral cortex. Human experts, Hinton notes, rarely articulate explicit deductive syllogisms when recognizing a face, diagnosing a rare radiological anomaly, or playing grandmaster chess; rather, they rely on subconscious, statistical pattern recognition distilled from years of perceptual experience. Proponents maintain that demanding full mathematical transparency from deep networks is an unreasonable double standard, given that human neurobiology is equally opaque to real-time introspective scrutiny.`,

      `[Paragraph 4] However, this optimistic equivalence is fiercely contested by cognitive scientists and causal epistemologists, prominently represented by Judea Pearl and Gary Marcus. Pearl argues that deep neural networks, regardless of their parameter scale, operate strictly on statistical correlations—associations within the lowest rung of his "Ladder of Causation." Deep models excel at answering questions of the form "if I observe variable X, what is the probability of Y?" but are intrinsically incapable of addressing causal interventional questions ("what happens if I do X?") or counterfactual reasoning ("what if X had not occurred?"). Because these models lack an internal causal ontology of the world, they are prone to brittle, catastrophic failures when confronted with out-of-distribution scenarios that deviate from training data.`,

      `[Paragraph 5] Gary Marcus reinforces this critique by highlighting the susceptibility of deep learning to "adversarial perturbations." By introducing imperceptible mathematical noise to an image of a panda, researchers can cause a state-of-the-art vision classifier to identify the image as a gibbon with 99.9% statistical confidence. Such bizarre vulnerabilities expose the foundational difference between human conceptual understanding and machine statistical curve-fitting: the network possesses no semantic comprehension of what an animal actually is, relying instead on high-dimensional pixel texture correlations.`,

      `[Paragraph 6] To mitigate this dangerous opacity, the burgeoning subfield of Explainable AI (XAI) has emerged. Researchers utilize post-hoc interpretability tools such as saliency maps and attention-weight heatmaps to render the model\'s internal representations intelligible to human auditors. Nevertheless, critics argue that many XAI methods merely generate superficial, persuasive rationalizations rather than revealing the true algorithmic mechanisms governing output determination.`,

      `[Paragraph 7] In synthesizing this profound debate, the author observes that conflating high-dimensional statistical pattern matching with genuine human intuition is a perilous category mistake. While deep learning has undeniably achieved extraordinary engineering triumphs, treating these models as autonomous oracles in high-stakes domains without causal verification invites systemic vulnerabilities. The future of robust artificial intelligence will not be achieved through parameter scaling alone, but through hybrid architectures that integrate the statistical power of connectionist networks with the rigorous, explainable causal ontology of symbolic reasoning.`
    ],
    nodes: [
      {
        id: 'node-hinton',
        label: 'Geoffrey Hinton & Yann LeCun',
        type: 'proponent',
        roleTitle: 'Connectionist Pioneers (Turing Laureates)',
        summary: 'Argue high-dimensional statistical induction mirrors human subconscious cortical intuition.',
        paragraphIndex: 3,
        keyQuotes: ['Statistical pattern recognition mirrors human expertise which also lacks introspective transparency.'],
        x: 180,
        y: 110,
        domain: 'Deep Learning / Connectionism'
      },
      {
        id: 'node-black-box',
        label: 'The Epistemic Black Box Paradox',
        type: 'concept',
        roleTitle: 'Core Construct',
        summary: 'High-dimensional non-linear weight manifolds yielding high predictive accuracy without mechanistic interpretability.',
        paragraphIndex: 2,
        keyQuotes: ['Constructs complex non-linear geometric manifolds in high-dimensional vector spaces.'],
        x: 400,
        y: 70,
        domain: 'Epistemic Concept'
      },
      {
        id: 'node-pearl',
        label: 'Judea Pearl & Gary Marcus',
        type: 'skeptic',
        roleTitle: 'Causal Inference & Cognitive AI (UCLA / NYU)',
        summary: 'Argue deep learning is mere curve-fitting stuck on statistical correlation, lacking causal models and counterfactual reasoning.',
        paragraphIndex: 4,
        keyQuotes: ['Deep models cannot answer interventional or counterfactual questions due to lack of causal ontology.'],
        x: 620,
        y: 110,
        domain: 'Causal AI & Symbolic Logic'
      },
      {
        id: 'node-adversarial',
        label: 'Adversarial Fragility & Texture Bias',
        type: 'concept',
        roleTitle: 'Empirical Vulnerability',
        summary: 'Imperceptible noise inducing catastrophic classification errors, proving absence of semantic understanding.',
        paragraphIndex: 5,
        keyQuotes: ['Imperceptible mathematical noise causing Panda to be classified as Gibbon.'],
        x: 620,
        y: 260,
        domain: 'Model Robustness'
      },
      {
        id: 'node-author-ai-stance',
        label: 'Authorial Synthesis',
        type: 'author_stance',
        roleTitle: 'Hybrid Neuro-Symbolic Imperative',
        summary: 'Warns against confusing statistical correlation with true intuition; demands integration of connectionist power with symbolic causal ontology.',
        paragraphIndex: 7,
        keyQuotes: ['Conflating statistical pattern matching with genuine intuition is a perilous category mistake.'],
        x: 400,
        y: 390,
        domain: 'Author Stance'
      }
    ],
    edges: [
      {
        id: 'edge-ai-1',
        source: 'node-hinton',
        target: 'node-black-box',
        relation: 'supports',
        label: 'Biện minh tính tương đương trực giác',
        evidenceSnippet: 'Leading connectionist pioneers argue that this statistical induction mirrors human intuition...',
        paragraphIndex: 3
      },
      {
        id: 'edge-ai-2',
        source: 'node-pearl',
        target: 'node-black-box',
        relation: 'undermines',
        label: 'Vạch trần giới hạn phi nhân quả',
        evidenceSnippet: 'Pearl argues that deep neural networks operate strictly on statistical correlations...',
        paragraphIndex: 4
      },
      {
        id: 'edge-ai-3',
        source: 'node-pearl',
        target: 'node-adversarial',
        relation: 'supports',
        label: 'Dẫn chứng bẫy nhiễu đối kháng',
        evidenceSnippet: 'Gary Marcus reinforces this critique by highlighting the susceptibility to adversarial perturbations...',
        paragraphIndex: 5
      },
      {
        id: 'edge-ai-4',
        source: 'node-author-ai-stance',
        target: 'node-black-box',
        relation: 'qualifies',
        label: 'Đề xuất kiến trúc lai Neuro-Symbolic',
        evidenceSnippet: 'The future will be achieved through hybrid architectures that integrate statistical power with causal ontology.',
        paragraphIndex: 7
      }
    ],
    constructs: [
      {
        id: 'cai-1',
        name: 'Epistemic Opacity / Black Box',
        definition: 'The condition where the internal logic and mathematical parameters of an AI system cannot be meaningfully inspected by humans.',
        implications: 'Precludes auditability in life-critical decision systems.',
        collocations: ['epistemic opacity', 'black-box algorithms', 'post-hoc interpretability', 'high-dimensional manifold']
      },
      {
        id: 'cai-2',
        name: 'Causal Ontology vs Statistical Correlation',
        definition: 'The structural understanding of cause-effect mechanisms versus the mere observation of mathematical co-occurrences.',
        implications: 'Distinguishes true commonsense understanding from brittle pattern matching.',
        collocations: ['causal inference', 'counterfactual reasoning', 'statistical curve-fitting', 'ladder of causation']
      }
    ],
    factions: {
      proponents: [
        {
          name: 'Geoffrey Hinton & Yann LeCun',
          institution: 'University of Toronto / Meta AI',
          coreClaim: 'Deep connectionist networks construct emergent intuitive representations akin to human perceptual cortex.',
          methodology: 'Large-scale gradient descent, backpropagation, high-dimensional vector embeddings.'
        }
      ],
      skeptics: [
        {
          name: 'Judea Pearl & Gary Marcus',
          institution: 'UCLA / Robust.AI',
          coreClaim: 'Deep learning is merely sophisticated statistical interpolation lacking causal models, prone to adversarial hallucinations.',
          methodology: 'Causal graphical models, counterfactual logic, adversarial vulnerability probing.'
        }
      ]
    },
    authorStance: {
      stanceType: 'cautious_synthesis',
      stanceTitle: 'Cảnh Báo Ảo Tưởng Trực Giác & Kêu Gọi Kiến Trúc Lai (Neuro-Symbolic Hybridism)',
      coreThesis: 'Khẳng định việc đánh đồng đối sánh thống kê với trực giác con người là sai lầm nghiêm trọng; kêu gọi kết hợp sức mạnh thống kê của mạng nơ-ron với tính minh bạch nhân quả của hệ thống logic biểu tượng.',
      keyHedgingExpressions: [
        'is a perilous category mistake',
        'while deep learning has undeniably achieved...',
        'treating these models as autonomous oracles... invites systemic vulnerabilities',
        'will not be achieved through parameter scaling alone'
      ],
      concludingParagraphIndex: 7,
      cambridgeTrapExplanation: 'Thí sinh dễ lầm tưởng tác giả bác bỏ toàn bộ Deep Learning vì những lỗ hổng Black Box. Tác giả thực chất công nhận thành tựu kỹ thuật nhưng cảnh báo việc phó thác quyết định sinh tử cho các mô hình phi nhân quả.'
    },
    summaryTask: {
      title: 'Summary Completion: The Epistemological Limits of Deep Learning',
      instructions: 'Complete the summary below using the Box of Options. Write the correct letter (A-J) for questions 1-5.',
      options: [
        { id: 'opt-A', term: 'opaque', ipa: '/oʊˈpeɪk/', definitionEn: 'Not able to be seen through; not easily understood.', definitionVi: 'mờ đục, bất khả minh bạch', band: 'C1', isDistractor: false },
        { id: 'opt-B', term: 'causal', ipa: '/ˈkɑː.zəl/', definitionEn: 'Relating to or acting as a cause.', definitionVi: 'mang tính nhân quả', band: 'C1', isDistractor: false },
        { id: 'opt-C', term: 'statistical', ipa: '/stəˈtɪs.tɪ.kəl/', definitionEn: 'Based on data analysis and probability patterns.', definitionVi: 'thuộc về thống kê xác suất', band: 'C1', isDistractor: false },
        { id: 'opt-D', term: 'heuristic', ipa: '/hjʊˈrɪs.tɪk/', definitionEn: 'Enabling someone to discover or learn something for themselves.', definitionVi: 'theo kinh nghiệm phỏng đoán', band: 'C2', isDistractor: false },
        { id: 'opt-E', term: 'symbolic', ipa: '/sɪmˈbɑː.lɪk/', definitionEn: 'Using explicit symbols and rules.', definitionVi: 'mang tính biểu tượng và quy tắc', band: 'C1', isDistractor: false },
        { id: 'opt-F', term: 'deductive', ipa: '/dɪˈdʌk.tɪv/', definitionEn: 'Characterized by the inference of particular instances from a general law.', definitionVi: 'diễn dịch suy luận', band: 'C1', isDistractor: true, distractorRationale: 'Thuộc AI truyền thống nhưng không khớp vị trí tóm tắt.' },
        { id: 'opt-G', term: 'fallible', ipa: '/ˈfæl.ə.bəl/', definitionEn: 'Capable of making mistakes or being erroneous.', definitionVi: 'dễ phạm sai lầm', band: 'C2', isDistractor: true, distractorRationale: 'Tính từ mô tả chung.' },
        { id: 'opt-H', term: 'autonomous', ipa: '/ɑːˈtɑː.nə.məs/', definitionEn: 'Acting independently without outside control.', definitionVi: 'tự chủ độc lập', band: 'C1', isDistractor: true, distractorRationale: 'Bẫy từ vựng công nghệ.' },
        { id: 'opt-I', term: 'parsimonious', ipa: '/ˌpɑːr.səˈmoʊ.ni.əs/', definitionEn: 'Very frugal or simple in explanation.', definitionVi: 'tiết kiệm, tinh gọn', band: 'C2', isDistractor: true, distractorRationale: 'Thuật ngữ triết học Ockham.' },
        { id: 'opt-J', term: 'emergent', ipa: '/ɪˈmɝː.dʒənt/', definitionEn: 'Becoming apparent or prominent.', definitionVi: 'mới nổi, phát sinh', band: 'C2', isDistractor: true, distractorRationale: 'Bẫy từ vựng hệ thống phức hợp.' }
      ],
      slots: [
        {
          id: 'slot-1',
          slotNumber: 1,
          preText: 'Unlike classical rule-based AI, modern deep learning networks operate as',
          correctTermId: 'opt-A',
          correctTerm: 'opaque',
          postText: 'black boxes that optimize millions of parameters across high-dimensional vector spaces.',
          explanation: 'Đoạn 1 và 2 mô tả nghịch lý "Black Box" và tính mờ đục ("opaque") của mạng nơ-ron sâu.',
          epistemicTrap: 'Bẫy chọn "deductive" do nhầm sang đặc tính của hệ thống AI truyền thống.'
        },
        {
          id: 'slot-2',
          slotNumber: 2,
          preText: 'Connectionist proponents claim this architecture mimics human intuition via subconscious',
          correctTermId: 'opt-D',
          correctTerm: 'heuristic',
          postText: 'pattern recognition developed through extensive experiential exposure.',
          explanation: 'Đoạn 3 phân tích lập luận của Hinton: chuyên gia con người đưa ra quyết định dựa trên phỏng đoán quy nạp ("heuristic, intuitive functioning").',
          epistemicTrap: 'Bẫy chọn "deductive" vì nghĩ chuyên gia sử dụng suy luận logic chặt chẽ.'
        },
        {
          id: 'slot-3',
          slotNumber: 3,
          preText: 'In contrast, critics such as Judea Pearl emphasize that deep learning relies merely on',
          correctTermId: 'opt-C',
          correctTerm: 'statistical',
          postText: 'correlations, making it incapable of answering intervention questions.',
          explanation: 'Đoạn 4 chỉ ra rằng các mô hình sâu chỉ hoạt động dựa trên các mối tương quan thống kê ("statistical correlations").',
          epistemicTrap: 'Bẫy chọn "emergent" do không để ý từ "correlations" ở phía sau.'
        },
        {
          id: 'slot-4',
          slotNumber: 4,
          preText: 'Because deep models lack an internal',
          correctTermId: 'opt-B',
          correctTerm: 'causal',
          postText: 'ontology of the physical world, they remain vulnerable to adversarial perturbations.',
          explanation: 'Đoạn 4 và 5 khẳng định mạng nơ-ron thiếu vắng một bản thể luận nhân quả ("internal causal ontology").',
          epistemicTrap: 'Bẫy chọn "symbolic" do nhầm lẫn giữa công cụ biểu tượng và mối quan hệ nhân quả.'
        },
        {
          id: 'slot-5',
          slotNumber: 5,
          preText: 'To achieve true reliability, the author advocates for hybrid systems merging deep learning with',
          correctTermId: 'opt-E',
          correctTerm: 'symbolic',
          postText: 'reasoning capable of clear causal explanations.',
          explanation: 'Đoạn 7 kết luận rằng tương lai của AI phải là kiến trúc lai kết hợp mạng nơ-ron với logic biểu tượng ("symbolic reasoning").',
          epistemicTrap: 'Bẫy chọn "heuristic" do đã dùng sai ở câu trước.'
        }
      ]
    }
  },
  {
    id: 'p3-04',
    title: 'The Temporal Disconnect: Human Chronobiology & Modern Mechanized Time',
    subtitle: 'Circadian Desynchrony, Industrial Clock-Time & Social Jetlag',
    category: 'Chronobiology & Sociology of Science',
    wordCount: 910,
    paragraphs: [
      `[Paragraph 1] In pre-industrial human history, the perception and organization of time were inextricably anchored to ecological rhythms. Human activity expanded and contracted in organic alignment with the diurnal cycle of the sun, the waxing and waning of lunar phases, and seasonal agricultural cycles. However, with the onset of the Industrial Revolution and the invention of precision mechanical escapements, this endogenous biological synchrony was severed. As cultural historian Lewis Mumford famously observed, the quintessential machine of the industrial age was not the steam engine, but the mechanical clock—an instrument that dissociated time from human experience, converting duration into a standardized, quantifiable, and merciless commodity.`,

      `[Paragraph 2] In recent decades, the biological consequences of this historical divorce have been illuminated by the burgeoning field of chronobiology. At the heart of human temporal physiology lies the Suprachiasmatic Nucleus (SCN)—a tiny cluster of approximately twenty thousand neurons situated within the anterior hypothalamus. Functioning as the body’s master pacemaker, the SCN coordinates the endogenous circadian rhythm (an approximate 24.2-hour cycle) across peripheral oscillators in every organ, synchronizing gene expression, hormone secretion (notably melatonin and cortisol), core body temperature, and immune function.`,

      `[Paragraph 3] Crucially, contemporary chronobiologists such as Till Roenneberg have demonstrated that circadian rhythms exhibit profound genetic heterogeneity across the human population, manifesting as distinct "chronotypes." Rather than conforming to a single moral archetype of the "early riser," individuals naturally range across a bell curve from extreme "larks" (morning chronotypes) to extreme "owls" (evening chronotypes). Roenneberg coined the term "Social Jetlag" to describe the chronic, systemic temporal misalignment between an individual’s genetically encoded biological clock and the rigid social schedules enforced by corporate workplaces and educational institutions.`,

      `[Paragraph 4] For evening chronotypes, who constitute over forty percent of the adolescent and young adult demographic, social jetlag represents a form of forced physiological sleep deprivation. Forcing an evening-type student or employee to perform high-stakes cognitive tasks at 8:00 AM is biologically equivalent to demanding that a daytime traveler function during severe transmeridian jetlag. Epidemiological research conducted by neuroscientist Russell Foster reveals that chronic circadian disruption is not merely an inconvenience; it elevates the risk of cardiovascular pathology, metabolic syndrome, clinical depression, and oncological risks through the systemic suppression of nocturnal cellular repair mechanisms.`,

      `[Paragraph 5] Despite this overwhelming empirical evidence, conventional socio-economic frameworks continue to enforce an archaic chrononormativity. Standardized 9-to-5 schedules, early school bell times, and the biannual disruption of Daylight Saving Time persist largely unabated. Proponents of rigid synchronization argue that synchronized working hours are indispensable for maintaining transaction efficiency, collaborative cohesion, and predictable economic logistics in global supply chains. They contend that decentralizing work schedules would precipitate organizational chaos and undermine collaborative synergy.`,

      `[Paragraph 6] Nevertheless, innovative ergonomic experiments in forward-thinking jurisdictions suggest that accommodating chronobiological diversity enhances rather than diminishes productivity. When high schools in Seattle delayed start times by fifty-five minutes, researchers documented a significant increase in median sleep duration, improved academic grades, and a measurable reduction in adolescent vehicular accidents. Similarly, corporate flex-time models that permit employees to align cognitive output with their personal peak circadian alertness have yielded dramatic decreases in burnout and absenteeism.`,

      `[Paragraph 7] In synthesizing these findings, the author asserts that the contemporary temporal disconnect is unsustainable. Modern society has reached an urgent inflection point: we must dismantle the moralistic prejudice that equates evening chronotypes with sloth and morningness with virtue. Moving forward, true public health reform requires aligning institutional chronopolitics with evolutionary biology—transitioning from the tyrannical, mechanized clock-time of the nineteenth century to a dynamic, chronobiologically enlightened social architecture.`
    ],
    nodes: [
      {
        id: 'node-mumford',
        label: 'Lewis Mumford',
        type: 'proponent',
        roleTitle: 'Cultural Historian',
        summary: 'Argued the mechanical clock, not the steam engine, was the core machine transforming time into a rigid commodity.',
        paragraphIndex: 1,
        keyQuotes: ['The clock dissociated time from human experience, converting duration into a standardized commodity.'],
        x: 180,
        y: 110,
        domain: 'History of Technology'
      },
      {
        id: 'node-circadian-scaffolding',
        label: 'Circadian Rhythm & SCN Pacemaker',
        type: 'concept',
        roleTitle: 'Biological Core Construct',
        summary: 'The master biological clock in the hypothalamus synchronizing 24-hour physiological and endocrine rhythms.',
        paragraphIndex: 2,
        keyQuotes: ['The SCN coordinates the endogenous circadian rhythm across peripheral oscillators.'],
        x: 400,
        y: 70,
        domain: 'Chronobiology'
      },
      {
        id: 'node-roenneberg',
        label: 'Till Roenneberg & Russell Foster',
        type: 'proponent',
        roleTitle: 'Chronobiologists (Munich / Oxford)',
        summary: 'Identified distinct genetic chronotypes, coined "Social Jetlag", and proved health costs of forced early schedules.',
        paragraphIndex: 3,
        keyQuotes: ['Social Jetlag represents chronic misalignment between biological clocks and rigid social schedules.'],
        x: 200,
        y: 260,
        domain: 'Circadian Medicine'
      },
      {
        id: 'node-economic-rationalists',
        label: 'Traditional Ergonomic Rationalists',
        type: 'skeptic',
        roleTitle: 'Corporate & Institutional Proponents',
        summary: 'Argue rigid standardized schedules are necessary for logistical cohesion, transaction efficiency, and supply chains.',
        paragraphIndex: 5,
        keyQuotes: ['Synchronized working hours are indispensable for maintaining transaction efficiency.'],
        x: 620,
        y: 110,
        domain: 'Industrial Chrononormativity'
      },
      {
        id: 'node-author-time-stance',
        label: 'Authorial Synthesis',
        type: 'author_stance',
        roleTitle: 'Chronobiological Public Health Reform',
        summary: 'Demands urgent dismantling of moralistic chrononormativity and institutional alignment with evolutionary biology.',
        paragraphIndex: 7,
        keyQuotes: ['Society must align institutional chronopolitics with evolutionary biology.'],
        x: 400,
        y: 390,
        domain: 'Author Stance'
      }
    ],
    edges: [
      {
        id: 'edge-t1',
        source: 'node-mumford',
        target: 'node-circadian-scaffolding',
        relation: 'qualifies',
        label: 'Phân tích sự chia cắt lịch sử',
        evidenceSnippet: 'This endogenous biological synchrony was severed by the mechanical clock...',
        paragraphIndex: 1
      },
      {
        id: 'edge-t2',
        source: 'node-roenneberg',
        target: 'node-circadian-scaffolding',
        relation: 'supports',
        label: 'Khám phá Social Jetlag & Chronotype',
        evidenceSnippet: 'Roenneberg coined the term Social Jetlag to describe the chronic misalignment...',
        paragraphIndex: 3
      },
      {
        id: 'edge-t3',
        source: 'node-economic-rationalists',
        target: 'node-circadian-scaffolding',
        relation: 'undermines',
        label: 'Bảo vệ lịch làm việc đồng bộ 9-to-5',
        evidenceSnippet: 'Proponents of rigid synchronization argue that synchronized working hours are indispensable...',
        paragraphIndex: 5
      },
      {
        id: 'edge-t4',
        source: 'node-author-time-stance',
        target: 'node-circadian-scaffolding',
        relation: 'supports',
        label: 'Cải cách thời gian biểu học thuật',
        evidenceSnippet: 'Moving forward, true public health reform requires aligning institutional chronopolitics with evolutionary biology.',
        paragraphIndex: 7
      }
    ],
    constructs: [
      {
        id: 'ct-1',
        name: 'Social Jetlag',
        definition: 'The chronic physiological mismatch between an individual\'s biological circadian chronotype and institutional schedules.',
        implications: 'Directly accounts for widespread cognitive impairment, metabolic syndrome, and academic underperformance.',
        collocations: ['social jetlag', 'circadian misalignment', 'chronotype heterogeneity', 'sleep debt']
      },
      {
        id: 'ct-2',
        name: 'Chrononormativity',
        definition: 'The cultural assumption that daytime activity and early rising represent moral virtues while night alertness indicates indolence.',
        implications: 'Creates systemic educational and workplace discrimination against evening chronotypes.',
        collocations: ['institutional chrononormativity', 'moralistic prejudice', 'inflexible chronometry', 'endogenous pacemaker']
      }
    ],
    factions: {
      proponents: [
        {
          name: 'Till Roenneberg & Russell Foster',
          institution: 'Ludwig Maximilian University of Munich / Oxford University',
          coreClaim: 'Human chronotypes are genetically fixed; forcing late types into early schedules induces metabolic and psychological damage.',
          methodology: 'Munich ChronoType Questionnaire (MCTQ), cortisol/melatonin assays, polysomnography.'
        }
      ],
      skeptics: [
        {
          name: 'Traditional Industrial Logisticians',
          institution: 'Standardized Workplace Management',
          coreClaim: 'Universal synchronous work schedules are vital for organizational coordination and economic throughput.',
          methodology: 'Supply chain optimization metrics, corporate attendance tracking.'
        }
      ]
    },
    authorStance: {
      stanceType: 'qualified_endorsement',
      stanceTitle: 'Cải Cách Thể Chế Theo Nhịp Sinh Học Tiến Hóa (Chronobiological Institutional Reform)',
      coreThesis: 'Tác giả ủng hộ mạnh mẽ việc xóa bỏ định kiến đạo đức về "người dậy sớm / thức muộn" và tái cấu trúc giờ học và làm việc linh hoạt theo đồng hồ sinh học tự nhiên.',
      keyHedgingExpressions: [
        'is unsustainable',
        'modern society has reached an urgent inflection point',
        'we must dismantle the moralistic prejudice',
        'transitioning from tyrannical mechanized time'
      ],
      concludingParagraphIndex: 7,
      cambridgeTrapExplanation: 'Bẫy đề thi hay hỏi về quan điểm tác giả đối với lập luận của phe kinh tế học: tác giả coi lập luận của phe kinh tế là lạc hậu và gây tổn hại sức khỏe cộng đồng lâu dài.'
    },
    summaryTask: {
      title: 'Summary Completion: The Impact of Industrial Time on Human Biology',
      instructions: 'Complete the summary below by choosing the correct terms from the Box of Options. Write the correct letter (A-J) for questions 1-5.',
      options: [
        { id: 'opt-A', term: 'endogenous', ipa: '/enˈdɑː.dʒə.nəs/', definitionEn: 'Originating from within an organism.', definitionVi: 'nội sinh, bắt nguồn từ bên trong cơ thể', band: 'C2', isDistractor: false },
        { id: 'opt-B', term: 'mechanized', ipa: '/ˈmek.ə.naɪzd/', definitionEn: 'Equipped with or controlled by machinery.', definitionVi: 'cơ giới hóa, áp đặt bằng máy móc', band: 'C1', isDistractor: false },
        { id: 'opt-C', term: 'desynchrony', ipa: '/diːˈsɪŋ.krə.ni/', definitionEn: 'The state of not operating at the same time or speed.', definitionVi: 'sự mất đồng bộ sinh học', band: 'C2', isDistractor: false },
        { id: 'opt-D', term: 'heterogeneity', ipa: '/ˌhet̬.ɚ.oʊ.dʒəˈniː.ə.t̬i/', definitionEn: 'The quality of being diverse in character or content.', definitionVi: 'tính đa dạng, không đồng nhất', band: 'C2', isDistractor: false },
        { id: 'opt-E', term: 'deleterious', ipa: '/ˌdel.əˈtɪr.i.əs/', definitionEn: 'Causing harm or damage.', definitionVi: 'gây hại, độc hại', band: 'C2', isDistractor: false },
        { id: 'opt-F', term: 'arbitrary', ipa: '/ˈɑːr.bə.trer.i/', definitionEn: 'Based on random choice or whim.', definitionVi: 'tùy tiện', band: 'C1', isDistractor: true, distractorRationale: 'Tính từ mang nghĩa ngẫu nhiên.' },
        { id: 'opt-G', term: 'physiological', ipa: '/ˌfɪz.i.əˈlɑː.dʒɪ.kəl/', definitionEn: 'Relating to normal healthy bodily functions.', definitionVi: 'thuộc về sinh lý học', band: 'C1', isDistractor: true, distractorRationale: 'Bẫy từ vựng sinh học chung.' },
        { id: 'opt-H', term: 'ubiquitous', ipa: '/juːˈbɪk.wə.t̬əs/', definitionEn: 'Present or found everywhere.', definitionVi: 'phổ biến khắp nơi', band: 'C1', isDistractor: true, distractorRationale: 'Tính từ mô tả độ phổ biến.' },
        { id: 'opt-I', term: 'resilient', ipa: '/rɪˈzɪl.jənt/', definitionEn: 'Able to recover quickly from difficult conditions.', definitionVi: 'kiên cường, đàn hồi', band: 'C1', isDistractor: true, distractorRationale: 'Tính từ mang nghĩa tích cực.' },
        { id: 'opt-J', term: 'synchronized', ipa: '/ˈsɪŋ.krə.naɪzd/', definitionEn: 'Occurring at the same time.', definitionVi: 'đồng bộ hóa', band: 'C1', isDistractor: true, distractorRationale: 'Dạng phân từ của đồng bộ.' }
      ],
      slots: [
        {
          id: 'slot-1',
          slotNumber: 1,
          preText: 'The Industrial Revolution marked a historic transition away from natural rhythms toward a',
          correctTermId: 'opt-B',
          correctTerm: 'mechanized',
          postText: 'form of clock-time that treated human activity as a standardized commodity.',
          explanation: 'Đoạn 1 phân tích sự trỗi dậy của đồng hồ cơ khí ("mechanical clock") và thời gian cơ giới hóa.',
          epistemicTrap: 'Bẫy chọn "arbitrary" do không phân biệt được thời gian công nghiệp cơ giới hóa với tính tùy tiện.'
        },
        {
          id: 'slot-2',
          slotNumber: 2,
          preText: 'Inside the human body, the Suprachiasmatic Nucleus regulates the',
          correctTermId: 'opt-A',
          correctTerm: 'endogenous',
          postText: 'circadian pacemaker that controls essential hormone secretions and cellular cycles.',
          explanation: 'Đoạn 2 giải thích cơ chế điều hòa đồng hồ sinh học nội sinh ("endogenous circadian rhythm").',
          epistemicTrap: 'Bẫy chọn "physiological" vì không nắm được tính từ chính xác mô tả nguồn gốc tự sinh trong cơ thể.'
        },
        {
          id: 'slot-3',
          slotNumber: 3,
          preText: 'Modern research proves that chronotypes exhibit vast genetic',
          correctTermId: 'opt-D',
          correctTerm: 'heterogeneity',
          postText: 'producing a natural distribution of morning larks and evening owls.',
          explanation: 'Đoạn 3 chỉ ra rằng nhịp sinh học thể hiện sự đa dạng di truyền sâu sắc ("genetic heterogeneity").',
          epistemicTrap: 'Bẫy chọn "desynchrony" do nhầm lẫn giữa tính đa dạng sinh học tự nhiên và sự lệch pha do xã hội áp đặt.'
        },
        {
          id: 'slot-4',
          slotNumber: 4,
          preText: 'When rigid school and corporate schedules force late chronotypes to awaken unnaturally early, it causes chronic',
          correctTermId: 'opt-C',
          correctTerm: 'desynchrony',
          postText: 'known clinically as Social Jetlag.',
          explanation: 'Đoạn 3 và 4 định nghĩa Social Jetlag là sự mất đồng bộ ("temporal misalignment / desynchrony") giữa đồng hồ sinh học và lịch xã hội.',
          epistemicTrap: 'Bẫy chọn "heterogeneity" nếu đã dùng sai ở câu trước.'
        },
        {
          id: 'slot-5',
          slotNumber: 5,
          preText: 'This mismatch has severe and',
          correctTermId: 'opt-E',
          correctTerm: 'deleterious',
          postText: 'effects on long-term metabolic, cardiovascular, and psychological health.',
          explanation: 'Đoạn 4 liệt kê các hậu quả gây hại nghiêm trọng ("deleterious / pathology / depression") của sự gián đoạn nhịp sinh học.',
          epistemicTrap: 'Bẫy chọn "arbitrary" do thiếu vốn từ vựng C2.'
        }
      ]
    }
  }
];
